// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeoo5pW1uOyNLXcLO8Cs7HcPSgetQW6as',
    appId: '1:69222755326:web:e1989f80d3f3aec6ce6eaf',
    messagingSenderId: '69222755326',
    projectId: 'airsense-delhi',
    authDomain: 'airsense-delhi.firebaseapp.com',
    storageBucket: 'airsense-delhi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY5KsSDoENXIGxVqm1OTMJ2xNc61pYmc8',
    appId: '1:69222755326:android:e7495eb1b9fa68fbce6eaf',
    messagingSenderId: '69222755326',
    projectId: 'airsense-delhi',
    storageBucket: 'airsense-delhi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_wIMPlHDbXgeoyULod5wfp7gTf-1qHQ',
    appId: '1:69222755326:ios:280ecd864400a649ce6eaf',
    messagingSenderId: '69222755326',
    projectId: 'airsense-delhi',
    storageBucket: 'airsense-delhi.firebasestorage.app',
    iosBundleId: 'com.example.airsenseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe_wIMPlHDbXgeoyULod5wfp7gTf-1qHQ',
    appId: '1:69222755326:ios:280ecd864400a649ce6eaf',
    messagingSenderId: '69222755326',
    projectId: 'airsense-delhi',
    storageBucket: 'airsense-delhi.firebasestorage.app',
    iosBundleId: 'com.example.airsenseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeoo5pW1uOyNLXcLO8Cs7HcPSgetQW6as',
    appId: '1:69222755326:web:c92f769e4a2da1bfce6eaf',
    messagingSenderId: '69222755326',
    projectId: 'airsense-delhi',
    authDomain: 'airsense-delhi.firebaseapp.com',
    storageBucket: 'airsense-delhi.firebasestorage.app',
  );
}
